import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const htmlUrl = new URL("../public/piano-roll/index.html", import.meta.url);
const jsUrl = new URL("../public/piano-roll/app.js", import.meta.url);
const cssUrl = new URL("../public/piano-roll/style.css", import.meta.url);

test("Piano Roll exposes autosave recovery and editing surfaces", async () => {
  const html = await readFile(htmlUrl, "utf8");
  assert.match(html, /<title>ShadowScore Piano Roll<\/title>/);
  assert.match(html, /data-shadow-nav/);
  assert.match(html, /<a href="\/piano-roll" aria-current="page">ShadowScore<\/a>/);
  assert.match(html, /<a href="\/structure-editor">Arrange<\/a>/);
  assert.match(html, /<a href="\/editors">OSC<\/a>/);
  assert.match(html, /<a href="\/">Setup<\/a>/);
  assert.match(html, /\/shared\/shadowscore-nav\.js/);
  assert.doesNotMatch(html, /id="save"/);
  assert.match(html, /Completed gestures save automatically/);
  assert.match(html, /id="revert"[^>]*disabled/);
  assert.match(html, /id="chase"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /Follow section/);
  assert.match(html, /id="scroll-chase"/);
  assert.match(html, /value="pages"/);
  assert.match(html, /value="centered"/);
  assert.match(html, /id="zoom-fit"/);
  assert.match(html, /id="pitch-labels"/);
  assert.match(html, /id="fold"[^>]*aria-pressed="false"/);
  assert.match(html, /id="roll"/);
  assert.match(html, /id="roll"[^>]*tabindex="0"/);
  assert.match(html, /id="roll-wiper"[^>]*class="wiper-overlay"/);
  assert.match(html, /id="velocity"/);
  assert.match(html, /id="velocity-wiper"[^>]*class="wiper-overlay"/);
  assert.match(html, /id="playback-update"/);
  assert.match(html, /id="note-menu"[^>]*role="menu"/);
  assert.match(html, /id="move-to"[^>]*aria-haspopup="menu"/);
  assert.match(html, /id="move-to-menu"[^>]*role="menu"/);
  assert.match(html, /id="import-midi"/);
  assert.match(html, /id="midi-import-dialog"/);
  assert.match(html, /id="midi-file"[^>]*type="file"/);
  assert.match(html, /id="midi-lanes"/);
  assert.match(html, /Each mapped lane creates a fresh one-shot clip/);
  assert.match(html, /Alt-click or right-click any visible note to orchestrate it/);
});

test("Piano Roll autosaves revision-aware clip drafts and supports right-edge resize", async () => {
  const js = await readFile(jsUrl, "utf8");
  assert.match(js, /expectedVersion:entry\.baseVersion/);
  assert.match(js, /kind:right-p\.x<=9\?"resize":"move"/);
  assert.match(js, /resizeNoteRight/);
  assert.match(js, /moveNote/);
  assert.match(js, /projectClipOccurrences/);
  assert.match(js, /\/playback\/snapshot/);
  assert.match(js, /playbackGeneration/);
  assert.match(js, /state\.playbackRequest/);
  assert.match(js, /createWiperEstimator/);
  assert.match(js, /createWiperEstimator\(\{staleAfterMs:3000,/);
  assert.match(js, /requestAnimationFrame/);
  assert.match(js, /renderWiperFrame/);
  assert.doesNotMatch(js, /function drawWiper/);
  assert.match(js, /addEventListener\("keydown"/);
  assert.match(js, /nudgeNote/);
  assert.match(js, /pointercancel",cancelDrag/);
  assert.match(js, /createClipDraftStore/);
  assert.match(js, /draftStore\.reconcile/);
  assert.match(js, /saving elsewhere/);
  assert.match(js, /dirtyClipIds/);
  assert.match(js, /expectedVersion:entry\.baseVersion/);
  assert.match(js, /state\.draft\.notes\.push/);
  assert.match(js, /duration:gridStep\(\)/);
  assert.match(js, /const referenceNotes = \(\) => Object\.values/);
  assert.match(js, /\.\.\.referenceNotes\(\)/);
  assert.match(js, /const visiblePitches = \(\) => state\.folded/);
  assert.match(js, /Array\.from\(\{length:128\},\(_,index\)=>127-index\)/);
  assert.match(js, /state\.top\+\(127-84\)\*rowHeight\(\)/);
  assert.match(js, /ui\.fold\.addEventListener\("click"/);
  assert.match(js, /ui\.chase\.addEventListener\("change"/);
  assert.match(js, /shadowscore\.pianoRoll\.followSection/);
  assert.match(js, /ui\.block\.disabled=state\.chasing/);
  assert.match(js, /function followChase\(\)/);
  assert.match(js, /blockId:sampleBlockId/);
  assert.match(js, /playheadScrollLeft/);
  assert.match(js, /zoomAnchorScrollLeft/);
  assert.match(js, /state\.playback\?\.activeBlockId\|\|state\.score\?\.structureState\?\.activeBlockId/);
  assert.match(js, /Autosave failed:/);
  assert.match(js, /function queueAutosave/);
  assert.match(js, /createPlaybackUpdateControl/);
  assert.match(js, /event\.altKey/);
  assert.match(js, /event\.button!==0/);
  assert.match(js, /hitOrchestrationNote/);
  assert.match(js, /hitTestNoteEntries/);
  assert.match(js, /orchestrationDestinations/);
  assert.match(js, /\/clips\/actions\/move-note/);
  assert.match(js, /shared_clip_confirmation_required/);
  assert.match(js, /destinationPlayerId/);
  assert.match(js, /Add players in Setup…/);
  assert.match(js, /Review assignments in Arrange…/);
  assert.match(js, /event\.key==="ContextMenu"/);
  assert.match(js, /event\.shiftKey&&event\.key==="F10"/);
  assert.match(js, /parseStandardMidiFile/);
  assert.match(js, /\/clips\/actions\/import-midi-to-players/);
  assert.match(js, /expectedStructureRevision:state\.score\.structureRevision/);
  assert.match(js, /Each MIDI lane needs a different destination player/);
});

test("Piano Roll uses the native vertical scrollbar for all MIDI pitches", async () => {
  const css = await readFile(cssUrl, "utf8");
  assert.match(css, /\.roll-scroll \{ overflow-y:scroll; \}/);
});
